# Generated by Django 3.0.6 on 2020-07-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='components_type',
            name='perf_list',
            field=models.ManyToManyField(help_text='select key performances of this component type', to='techno.Key_Perf'),
        ),
    ]
