# Generated by Django 3.1.4 on 2020-12-29 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0004_auto_20201228_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technos_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='techno',
            name='node_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='key_perf',
            name='component',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='techno.component'),
        ),
        migrations.AlterField(
            model_name='key_perf',
            name='key_param',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='techno.key_param'),
        ),
    ]
