# Generated by Django 3.1.4 on 2020-12-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0005_auto_20201229_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='techno',
            name='techno_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='techno.technos_type'),
        ),
        migrations.AlterField(
            model_name='key_perf',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='techno.component'),
        ),
        migrations.AlterField(
            model_name='key_perf',
            name='key_param',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='techno.key_param'),
        ),
        migrations.AlterField(
            model_name='techno',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='techno.provider'),
        ),
    ]
