# Generated by Django 3.1.4 on 2020-12-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0006_auto_20201229_1108'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='key_perf',
            constraint=models.UniqueConstraint(fields=('component', 'key_param'), name='perf_record'),
        ),
    ]
