# Generated by Django 3.1.4 on 2020-12-31 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0007_auto_20201229_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='comp_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techno.components_type', verbose_name='component type'),
        ),
        migrations.AlterField(
            model_name='key_param',
            name='units',
            field=models.CharField(blank=True, choices=[('Hz', 'Hz'), ('W', 'W'), ('%', '%'), ('dB', 'Db')], max_length=10),
        ),
    ]
